### ISSUE TITLE
Access to Course Code

### ISSUE THREAD

**Issue by dkent287** [bzaharatos/-Statistical-Modeling-for-Data-Science-Applications#1]
Statistical Modeling for Data Science Applications Specialization is a fantastic set of courses!

Is it possible to add the code used in the lectures to this repo (or some other location)?

**Comment by bzaharatos** [comment]
Thanks for your kind words! Let me check on whether I'm allowed to post the code, based on our agreement with Coursera.

**Comment by dkent287** [comment]
I see the code is now on the site - vb thank-you!
